name: Create new workspace

on:
  pull_request:
    # types: [opened]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Create new workspace
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create branch workspace
        uses: dflook/terraform-new-workspace@v1
        with:
          workspace: ${{ github.head_ref }}
